version: '3'
services:
  firebase-cf:
    image: node6-firebase
    command: firebase serve --only functions --host 0.0.0.0
    ports:
      - "5000"
    volumes:
      - ./dot.config:/root/.config # firebase config
      - .:/project
